[package]
name = "tobii5-init-replay"
version = "0.1.0"
edition = "2021"

[lib]
name = "tobii"
crate-type = ["rlib", "cdylib"]
path = "src/lib.rs"

[[bin]]
name = "tobii5-init-replay"
path = "src/main.rs"

[[bin]]
name = "tobiid"
path = "src/bin/tobiid.rs"

[[bin]]
name = "tobii-opentrack"
path = "src/bin/tobii_opentrack.rs"

[[bin]]
name = "tobii-gaze-keys"
path = "src/bin/tobii_gaze_keys.rs"

[dependencies]
anyhow = "1"
libc = "0.2"
ort = "2.0.0-rc.10"
rusb = "0.9"
