#!/usr/bin/env python3
"""Write the head pose test vectors: small synthetic cases whose expected outputs reference.py
computes, which tobii-pose's head.rs tests carry as literals.

    make_vectors.py OUT.json [--params FIT.json] [--eye-weight W|fitted] [--rotation-filters ...]

No session data goes in. The rotations, translations and angles are made up; the landmarks are
the canonical face mesh of crates/tobii-pose/src/canonical.rs (MediaPipe's, not the user's face)
projected with made-up poses and rounded to 1e-4 px, and the expected outputs are computed from
the rounded inputs. With the default constants (reference.PROTOTYPE) the file is byte for byte
the head pose study's test_vectors.json (its "about" still names the study's folder), which is
what head.rs's tests were taken from and still carry: they check the arithmetic, which needs
no other constants than these.

--params takes fit.py's JSON (its head_params) instead, for vectors of a fit's constants. To keep
the eye branch and the per-axis filters covered as the study's vectors do, give the eye weight the
fit found (--eye-weight fitted) and --rotation-filters per-axis: the vectors' "constants" block
then says what the tests must build.
"""

import argparse
import json
import math
import os
import re
import sys

import numpy as np

HERE = os.path.dirname(os.path.abspath(__file__))
sys.path.insert(0, HERE)
import reference as ref  # noqa: E402

CANONICAL_RS = os.path.join(HERE, "..", "..", "crates", "tobii-pose", "src", "canonical.rs")
# The Windows sessions' display area: area A of the study.
AREA_A = ref.WINDOWS_AREA
DT = 30208  # us, the 0x50e image interval
# Made-up inputs the study drew from np.random.default_rng(20260929), written out because NumPy
# does not promise the same stream from one version to the next: four more angle triples for the
# yxz vectors (deg, rounded to 0.001; x, y, z) and six poses for the position model ((pitch, yaw,
# roll) deg about the usual pose under the tilted camera, then the translation, mm).
EULER_DRAWN_DEG = [
    [-17.97, 34.167, 1.72],
    [-49.203, -59.895, 4.728],
    [-16.431, 18.737, 22.29],
    [-25.466, -21.65, 1.816],
]
POSITION_POSES = [
    (
        (8.491327844467689, 9.806499420607821, 2.901115771815313),
        (-27.524850807863743, -16.81878251724813, 573.497310874498),
    ),
    (
        (3.9528252701317497, -17.361478593378493, 14.4616798078793),
        (19.59008322953075, -13.900598287519477, 577.9997776123156),
    ),
    (
        (1.5619489193125893, -8.0792100114441, -2.4628542086325025),
        (55.1954939229997, 2.384865646955536, 602.2696806150905),
    ),
    (
        (15.191364435524271, -2.4664280660131332, -4.2536552910970435),
        (-25.093009705258464, -22.040093297034492, 631.5743791297155),
    ),
    (
        (4.5506868124740425, -1.938292752559224, 9.135021943708843),
        (-35.22009439555708, -3.1235538232141344, 591.7268269139147),
    ),
    (
        (4.280924717853239, -23.530308059521587, 6.79811528349492),
        (-11.839186504535812, -26.169900675208407, 598.9327045298605),
    ),
]


def canonical_mm(path):
    """The canonical face mesh of canonical.rs (468 x 3, cm as f32) in mm."""
    with open(path) as f:
        txt = f.read()
    body = txt[txt.index("= [") + 3 :]
    pts = re.findall(r"\[\s*(-?[\d.eE+-]+),\s*(-?[\d.eE+-]+),\s*(-?[\d.eE+-]+)\s*\]", body)
    a = np.array(pts, dtype=np.float32).astype(np.float64)
    if a.shape != (468, 3):
        sys.exit(f"{path}: {a.shape[0]} vertices, not 468")
    return 10.0 * a


def L(a):
    return np.asarray(a, float).tolist()


def jparams(P):
    out = {}
    for k, v in P.items():
        if isinstance(v, np.ndarray):
            out[k] = v.tolist()
        elif isinstance(v, dict):
            out[k] = {kk: list(vv) for kk, vv in v.items()}
        else:
            out[k] = v
    return out


def vectors(P, canon_mm):
    """The vectors' document for constants P."""
    Q = np.asarray(P["Q"], float)
    R_TS, c = ref.display_frame(*AREA_A)
    cmin, nmin = P["g3_centroid_min_px"], P["g3_nose_min_px"]

    def project(R_cam, t_cam_mm):
        X = canon_mm @ np.asarray(R_cam).T + np.asarray(t_cam_mm)
        return np.round(
            np.stack([376.0 * X[:, 0] / X[:, 2] + 140.0, 376.0 * X[:, 1] / X[:, 2] + 140.0], 1), 4
        )

    def cam_pose(pitch, yaw, roll, t):
        """A made-up object -> camera rotation about the usual pose under a tilted camera (which
        looks up ~24 deg)."""
        return (
            ref.rx(math.radians(24.0 + pitch))
            @ ref.ry(math.radians(yaw))
            @ ref.rz(math.radians(roll)),
            np.array(t, float),
        )

    V = {
        "about": "Synthetic, face-free vectors generated by reference.py (work2/final-variant). "
        "Angles in radians unless the key says deg; positions mm; matrices row-major nested lists; "
        "landmark arrays = the generic canonical mesh (canonical.rs) projected with made-up poses "
        "(u = 376 X/Z + 140, v = 376 Y/Z + 140), rounded to 1e-4 px. Suggested tolerance: 1e-9 "
        "relative on angles/positions (all formulas are closed form in f64).",
        "constants": jparams(P),
        "display_area": {"TL": AREA_A[0], "TR": AREA_A[1], "BL": AREA_A[2]},
    }

    # A. the yxz decomposition
    tri = [
        [0, 0, 0],
        [20, 0, 0],
        [0, 30, 0],
        [0, 0, 25],
        [15, 25, 0],
        [15, 0, 20],
        [0, 25, 20],
        [-20, 30, -15],
        [25, -35, 10],
        [-10, -40, 30],
        [-35, 0, 0],
        [0, -60, 0],
        [0, 0, -45],
        [41, 59, -30],
    ]
    tri += [list(a) for a in EULER_DRAWN_DEG]
    va = []
    for a in tri:
        x, y, z = (math.radians(v) for v in a)
        R = ref.compose_yxz(x, y, z)
        va.append(
            dict(
                angles_deg_xyz=a,
                R=L(R),
                euler_yxz=list(ref.euler_yxz(R)),
                wrong_zyx_reading=list(ref.euler_zyx(R)),
            )
        )
    V["euler_yxz"] = {
        "note": "R = Ry(y) Rx(x) Rz(z); euler_yxz(R) must return (x, y, z); wrong_zyx_reading = "
        "what R = Rz Ry Rx decomposition would report (must NOT be used)",
        "vectors": va,
    }

    # B. the display frame
    areas = {
        "A (Windows sessions)": AREA_A,
        "rolled 3 deg + sheared (synthetic)": (
            np.array([-300.0, 330.0, 110.0]),
            np.array([298.6, 361.3, 110.0]),
            np.array([-290.0, 10.0, -3.0]),
        ),
    }
    vb = []
    for name, (TL, TR, BL) in areas.items():
        R, cc = ref.display_frame(TL, TR, BL)
        pts = [[0.0, 150.0, 600.0], [-40.0, 60.0, 550.0], [55.5, 120.25, 700.0]]
        vb.append(
            dict(
                name=name,
                TL=L(TL),
                TR=L(TR),
                BL=L(BL),
                R_TS=L(R),
                c=L(cc),
                t=L(-R @ cc),
                points_S=pts,
                points_T=[L(R @ (np.array(p) - cc)) for p in pts],
            )
        )
    V["display_frame"] = {
        "note": "p_T = R_TS (p_S - c); rows of R_TS = x^, y^ (Gram-Schmidt), z^",
        "vectors": vb,
    }

    # C. the rotation
    vc = []
    for p, y_, r_ in [(0, 0, 0), (-10, 20, 5), (8, -30, -12), (15, 25, 18), (-20, -45, 10)]:
        Rc, _ = cam_pose(p, y_, r_, [0, 0, 600])
        H = ref.head_S(Rc, Q)
        RT = R_TS @ H
        vc.append(dict(R_cam=L(Rc), H_S=L(H), R_T=L(RT), rotation_xyz=list(ref.euler_yxz(RT))))
    V["rotation"] = {
        "note": "area A, Q = constants.Q: H_S = D R_cam D Q, R_T = R_TS H_S, rotation_xyz = "
        "euler_yxz(R_T) (unfiltered)",
        "vectors": vc,
    }

    # D. the position model (one image, unfiltered)
    vd = []
    for angles, t in POSITION_POSES:
        Rc, tc = cam_pose(*angles, list(t))
        lm = project(Rc, tc)
        ea, eb = ref.eye_points(lm)
        H = ref.head_S(Rc, Q)
        pp = ref.p_pnp_S(tc, H, P)
        pe = ref.p_eye_S(ea, eb, H, P)
        cor = P["w"] * (pe - pp)
        vd.append(
            dict(
                R_cam=L(Rc),
                t_cam_mm=L(tc),
                eye_a_px280=L(ea),
                eye_b_px280=L(eb),
                H_S=L(H),
                p_pnp_S=L(pp),
                p_eye_S=L(pe),
                correction_S=L(cor),
                p_raw_S=L(pp + cor),
                p_raw_T=L(R_TS @ (pp + cor - c)),
                p_pnp_only_T=L(R_TS @ (pp - c)),
            )
        )
    V["position_model"] = {
        "note": "eye_a / eye_b = centroids of the image-left / image-right eye-contour landmarks "
        "(given here directly); p_raw = p_pnp + w (p_eye - p_pnp) before any filter; T via "
        "area A",
        "vectors": vd,
    }

    # E. the validity rule G3 about its thresholds
    Rc0, tc0 = cam_pose(0, 0, 0, [0, -10, 620])
    base = project(Rc0, tc0)
    cen = base.mean(0)
    cases = []

    def g3case(name, lm, face=True, score=12.5):
        ok, ce, ne = ref.g3(face, score, lm, cmin, nmin)
        cases.append(
            dict(
                name=name,
                face=face,
                score=score,
                lm280=L(lm),
                valid=bool(ok),
                centroid_edge_px=None if not np.isfinite(ce) else ce,
                nose_edge_px=None if not np.isfinite(ne) else ne,
            )
        )

    def num(x):
        return f"{round(x, 9):g}"

    above_c, below_c = round(cmin + 0.1, 9), round(cmin - 0.1, 9)
    above_n, below_n = round(nmin + 0.1, 9), round(nmin - 0.1, 9)
    for tgt in (above_c, below_c):
        lm = np.round(base + np.array([tgt - cen[0], 0.0]), 4)
        g3case(f"centroid {num(tgt)} px from the left edge", lm)
    for tgt in (above_c, below_c):
        lm = np.round(base + np.array([0.0, tgt - cen[1]]), 4)
        g3case(f"centroid {num(tgt)} px from the top edge (nose inside)", lm)
    for tgt in (above_n, below_n):
        lm = np.round(base + np.array([(280.0 - 40.0) - cen[0], 0.0]), 4)
        lm[ref.NOSE_TIP] = [280.0 - tgt, lm[ref.NOSE_TIP][1]]
        g3case(f"nose tip {num(-tgt)} px beyond the right edge (centroid inside)", lm)
    for tgt in (above_n, below_n):
        lm = np.round(base.copy(), 4)
        lm[ref.NOSE_TIP] = [lm[ref.NOSE_TIP][0], tgt]
        g3case(f"nose tip {num(-tgt)} px beyond the top edge", lm)
    g3case("face with score -0.5 (no face)", np.round(base, 4), score=-0.5)
    g3case("face flag false", np.round(base, 4), face=False, score=float("nan"))
    for cse in cases:
        if not np.isfinite(cse["score"]):
            cse["score"] = None
    V["g3"] = {
        "note": "valid = face AND score >= 0 AND edge(mean of the 468 points) >= "
        f"{num(cmin)} AND edge(point 1) >= {num(nmin)}, edge(u, v) = min(u, 280 - u, v, 280 - v)",
        "cases": cases,
    }

    # F. the filters (Smoother alone)
    tl = [0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 60, 61, 62]  # image numbers; 10 -> 60 = 1.51 s
    valid = [1, 1, 1, 1, 0, 0, 0, 1, 1, 1, 1, 1, 1, 0]
    t_us = [k * DT + (3 if k % 3 == 1 else 0) for k in tl]  # a little jitter in the times
    pnp = [[10.0 + 2.0 * k, 100.0 - 1.5 * k, 600.0 + 3.0 * (k % 5)] for k in range(len(tl))]
    cor = [[0.5 * math.sin(k), -0.3 * math.cos(k), 1.0 + 0.1 * k] for k in range(len(tl))]
    ang = [
        [5.0 + 1.2 * k + 0.3 * (-1) ** k, -10.0 + 4.0 * k, 2.0 - 0.7 * k] for k in range(len(tl))
    ]
    vf = {}
    for rule in ("timeaware", "reset"):
        sm = ref.Smoother(
            P["tau_pos_s"],
            P["tau_beta_s"],
            P["one_euro"],
            P["one_euro_dcut_hz"],
            P["reset_gap_s"],
            rule,
        )
        rows = []
        for i in range(len(tl)):
            if not valid[i]:
                sm.invalid()
                rows.append(dict(t_us=t_us[i], valid=False))
                continue
            y, rot, dt, reset = sm.valid(t_us[i], np.array(pnp[i]), np.array(cor[i]), ang[i])
            rows.append(
                dict(
                    t_us=t_us[i],
                    valid=True,
                    p_pnp_S=pnp[i],
                    correction_S=cor[i],
                    angles_deg=ang[i],
                    dt_s=dt,
                    reset=reset,
                    out_S=L(y),
                    out_angles_deg=L(rot),
                )
            )
        vf[rule] = rows
    # an angle crossing +-180 deg (one-euro alone)
    oe = ref.OneEuro(*P["one_euro"]["y"], P["one_euro_dcut_hz"])
    seq = [178.0, 179.5, -179.0, -177.5, -178.0]
    wrap_rows = [dict(x_deg=seq[0], out_deg=oe.reset(seq[0]))]
    for xv in seq[1:]:
        wrap_rows.append(dict(x_deg=xv, out_deg=oe.step(xv, DT * 1e-6)))
    V["filters"] = {
        "note": "reference.Smoother with constants.tau_pos_s / tau_beta_s / one_euro; frames 4-6 "
        "invalid (gap: dt of frame 7 = 4 frames under timeaware), frame 11 comes 1.51 s after "
        "frame 10 (> 1 s: hard reset under both rules), frame 13 invalid; out_S = filtered p_pnp + "
        "low-passed correction (S, mm)",
        "rules": vf,
        "one_euro_wrap_yaw": {
            "fmin_beta": list(P["one_euro"]["y"]),
            "dcut_hz": P["one_euro_dcut_hz"],
            "dt_s": DT * 1e-6,
            "rows": wrap_rows,
        },
    }

    # G. the whole estimator over one input sequence, per (rule, model)
    poses = [
        (0, 0, 0, [5, -20, 620]),
        (1, 2, 0.5, [6, -19, 621]),
        (2, 4, 1, [8, -18, 622]),
        (3, 6, 1.5, [10, -18, 624]),
        (3, 8, 2, [12, -17, 625]),
        None,
        None,
        None,
        (6, 20, 4, [30, -10, 630]),
        "edge",
        (7, 24, 5, [35, -8, 632]),
        (2, -5, -3, [-20, -25, 600]),
        (1, -6, -3, [-22, -25, 601]),
        "noscore",
        (0, -7, -2, [-24, -24, 603]),
    ]
    tfr = [0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 60, 61, 62, 63]
    inputs = []
    for fr, p in zip(tfr, poses):
        t = fr * DT
        if p is None:
            inputs.append(
                dict(t_us=t, face=False, score=None, R_cam=None, t_cam_mm=None, lm280=None)
            )
            continue
        if p == "edge":
            Rc, tc = cam_pose(6, 22, 4, [32, -9, 631])
            lm = project(Rc, tc)
            lm = np.round(
                lm + np.array([(cmin - 0.1) - lm.mean(0)[0], 0.0]), 4
            )  # centroid just short of G3
            sc = 9.0
        elif p == "noscore":
            Rc, tc = cam_pose(0, -6, -2, [-23, -24, 602])
            lm = project(Rc, tc)
            sc = -1.25
        else:
            Rc, tc = cam_pose(p[0], p[1], p[2], p[3])
            lm = project(Rc, tc)
            sc = 15.0
        inputs.append(dict(t_us=t, face=True, score=sc, R_cam=L(Rc), t_cam_mm=L(tc), lm280=L(lm)))
    frames = []
    for rule in ("timeaware", "reset"):
        for model in ("BLlp", "PnP-only"):
            Pm = dict(P)
            if model == "PnP-only":
                Pm["w"] = 0.0
            est = ref.HeadPoseEstimator(Pm, AREA_A, rule=rule)
            rows = []
            for inp in inputs:
                if not inp["face"]:
                    r = est.step(inp["t_us"], False, float("nan"), None, None, None)
                else:
                    r = est.step(
                        inp["t_us"],
                        True,
                        inp["score"],
                        np.array(inp["R_cam"]),
                        np.array(inp["t_cam_mm"]),
                        np.array(inp["lm280"]),
                    )
                dbg = dict(
                    g3_centroid_edge_px=r["g3_centroid_edge_px"]
                    if np.isfinite(r["g3_centroid_edge_px"])
                    else None,
                    g3_nose_edge_px=r["g3_nose_edge_px"]
                    if np.isfinite(r["g3_nose_edge_px"])
                    else None,
                )
                if r["valid"]:
                    dbg.update(
                        raw_rotation_deg=L(r["raw_rot_deg"]),
                        raw_pnp_S=L(r["raw_pnp_S"]),
                        raw_correction_S=None if r["raw_cor_S"] is None else L(r["raw_cor_S"]),
                        filtered_S=L(r["filt_S"]),
                        dt_s=r["dt_s"],
                        filter_reset=bool(r["filter_reset"]),
                    )
                rows.append(
                    dict(
                        valid=bool(r["valid"]),
                        position_mm=L(r["position_mm"]),
                        rotation_rad=L(r["rotation_rad"]),
                        debug=dbg,
                    )
                )
            frames.append(dict(rule=rule, model=model, outputs=rows))
    V["estimator_sequences"] = {
        "note": "reference.HeadPoseEstimator(constants, area A), one step per input frame; frames "
        "at t = n x 30208 us; frames 5-7 no face; frame 9 face but centroid "
        f"{num(cmin - 0.1)} px from the left edge (G3-invalid); frame 11 comes 1.51 s "
        "after frame 10 (hard reset); frame 13 face score < 0 (invalid). Invalid frames "
        "repeat the last valid values with valid = false. PnP-only = constants with w = "
        "0.",
        "inputs": inputs,
        "sequences": frames,
    }
    return V, dict(
        va=va, vb=vb, vc=vc, vd=vd, cases=cases, vf=vf, wrap_rows=wrap_rows, frames=frames
    )


def summary(parts, path):
    """make_params_vectors.out's lines."""
    p = parts
    print(
        f"{os.path.basename(path)}: {len(p['va'])} euler, {len(p['vb'])} display frames, "
        f"{len(p['vc'])} rotation, {len(p['vd'])} position, {len(p['cases'])} G3 cases, filter "
        f"sequences {list(p['vf'])} + wrap, {len(p['frames'])} estimator sequences; "
        f"{os.path.getsize(path) / 1024:.0f} KiB"
    )
    for cse in p["cases"]:
        print(
            f"  G3 {cse['name']}: valid {cse['valid']} (centroid edge {cse['centroid_edge_px']}, "
            f"nose edge {cse['nose_edge_px']})"
        )
    for fs in p["frames"]:
        print(
            f"  sequence {fs['rule']} / {fs['model']}: valid "
            + "".join("1" if r["valid"] else "0" for r in fs["outputs"])
            + "; resets at "
            + ",".join(
                str(i)
                for i, r in enumerate(fs["outputs"])
                if r["valid"] and r["debug"]["filter_reset"]
            )
        )
    for rule, rows in p["vf"].items():
        print(
            f"  filters {rule}: resets at "
            + ",".join(str(i) for i, r in enumerate(rows) if r["valid"] and r["reset"])
            + f"; dt of frame 7 = {rows[7]['dt_s']}"
        )
    print("  wrap: " + ", ".join(f"{r['x_deg']} -> {r['out_deg']:.4f}" for r in p["wrap_rows"]))


def main():
    ap = argparse.ArgumentParser(description=__doc__.split("\n\n")[0])
    ap.add_argument("out", help="the vectors' JSON to write")
    ap.add_argument(
        "--params", help="fit.py's JSON (its head_params) instead of the study's constants"
    )
    ap.add_argument(
        "--eye-weight",
        help="the eye weight w for the vectors: a number, or 'fitted' (the one fit.py "
        "found, from --params)",
    )
    ap.add_argument(
        "--rotation-filters",
        choices=("per-axis", "shared"),
        help="the study's one-euro filter per axis, or the one shared by the three angles, in "
        "place of the constants'",
    )
    ap.add_argument(
        "--canonical", default=CANONICAL_RS, help="canonical.rs to take the face mesh from"
    )
    args = ap.parse_args()

    doc = {}
    if args.params:
        with open(args.params) as f:
            doc = json.load(f)
        P = ref.params_from_head_params(doc.get("head_params", doc))
    else:
        P = dict(ref.PROTOTYPE)
    if args.eye_weight == "fitted":
        if "fit" not in doc:
            sys.exit("--eye-weight fitted needs fit.py's JSON in --params")
        P["w"] = doc["fit"]["eye_weight"]
    elif args.eye_weight is not None:
        P["w"] = float(args.eye_weight)
    if args.rotation_filters:
        src = ref.ONE_EURO_PER_AXIS if args.rotation_filters == "per-axis" else ref.ONE_EURO_SHARED
        P["one_euro"] = {k: list(v) for k, v in src.items()}

    V, parts = vectors(P, canonical_mm(args.canonical))
    with open(args.out, "w") as f:
        json.dump(V, f, separators=(",", ":"))
    summary(parts, args.out)


if __name__ == "__main__":
    main()
